#!/bin/bash
ipv4=$(curl --connect-timeout 5 -s ipv4.icanhazip.com)
sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
po=$(cat /etc/ssh/sshd_config | grep "^Port")
port=$(echo "$po" | sed "s/Port //g")
ipv6=$(curl --connect-timeout 5 -s ipv6.icanhazip.com)
panelversion=$(cat /var/www/html/p/version.txt)
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
CYAN="\e[36m"
ENDCOLOR="\e[0m"
adminuser=$(mysql -s -N -e  "use ShaHaN;select adminuser from setting where id='1';")
adminpass=$(mysql -s -N -e  "use ShaHaN;select adminpassword from setting where id='1';")
usercount=$(mysql -s -N -e  "use ShaHaN;select COUNT(*) from users;")
activeuser=$(mysql -s -N -e  "use ShaHaN;select COUNT(*) from users where enable='true';")
deactiveuser=$(mysql -s -N -e  "use ShaHaN;select COUNT(*) from users where enable not like 'true';")
online=$(sudo lsof -i  -n | grep " 4u" | grep -v root | grep ESTABLISHED | grep -v "videocall" | wc -l)





if ! [ $(id -u) = 0 ]; then
   echo -e "${RED}Plese run the command with root privilages!${ENDCOLOR}"
   exit 1
fi

clear
echo -e "${YELLOW}************ ShaHaN SSH PANEL ************"
echo -e "${RED}-----------------------------------\n"
echo -e "${YELLOW}-------- Server Details -----------\n"
echo -e "${GREEN}IPv4 : $ipv4"
echo -e "Ipv6 : $ipv6"
echo -e "SSH port : $port"
echo -e "Panel Version : $panelversion"
echo -e "Panel Link : http://$ipv4/p/index.php"
echo -e "Panel User : $adminuser"
echo -e "Panel Password : $adminpass"
echo -e "\n"
echo -e "Users Count : $usercount"
echo -e "Active Users : $activeuser"
echo -e "${RED}Deactive Users : $deactiveuser${ENDCOLOR}"

echo -e "${YELLOW}Online Users : $online${ENDCOLOR}"


echo -e "\n"
echo -e "${RED}-----------------------------------\n"
echo -e "${CYAN}  1)Instal & Update Panel"
echo -e "  2)Install SSH-Calls"
echo -e "  3)Install SSL For Domain"
echo -e "  4)Change SSH Port"
echo -e "  5)Block Iran IP ( Outgoing )"
echo -e "  6)Change Panel Port"
echo -e "  7)Forgot Password & ERROR-500"
echo -e "  8)Backup Users"
echo -e "  9)Remove ShaHaN"
echo -e "  10)${GREEN}Install Cisco Anyconnect ${ENDCOLOR}"
echo -e "\n"
echo -e "  20)${RED}Remove CisCo Anyconnect${ENDCOLOR}"
echo -e "${CYAN}  21)${RED}Remove SSL${ENDCOLOR}"
echo -e "${CYAN}  22)${RED}Remove Apache And PHP${ENDCOLOR}"
echo -e "${CYAN}  23)${RED}Disable IPV6${ENDCOLOR}"
echo -e "\n"
echo -e "  0)Exit"

echo -ne "${GREEN}\nSelect Operation : ${ENDCOLOR}" ;read n

case $n in
  1) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/install.sh --ipv4) ;;
  2) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/ssh-calls.sh --ipv4) ;;
  3) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/ssl.sh --ipv4) ;;
  4) echo  -ne "${YELLOW}Please enter new port: ";read new_port;sudo sed -i "s@Port $port@Port $new_port@g" /etc/ssh/sshd_config;systemctl restart sshd;echo "Port Changed Successfully${ENDCOLOR}";;
  5) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/newblockiran.sh --ipv4) ;;
  6) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/screenshot/chp.sh --ipv4) ;;
  7) mysql -e "use ShaHaN;update setting set adminuser='' and adminpassword='' where id=1;drop user $adminuser@localhost;" ;bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/install.sh --ipv4) ;;  
  8) mysqldump -u root ShaHaN > /root/bckup-new.sql || echo "New Backup Created : /root/bckup-new.sql";;
  9) rm -fr /var/www/html/*;;
  10) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ocserv-Ubuntu/main/c.sh --ipv4) ;;
  20) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ocserv-Ubuntu/main/rc.sh --ipv4) ;;
  21) rm -fr /etc/apache2/conf-available/ssl-params.conf && rm -fr /etc/apache2/sites-available/default-ssl.conf && systemctl restart apache2;;
  22) apt purge php* php8* php7* apache2 -y && apt autoremove -y;;
  23) bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/disableipv6.sh --ipv4) ;;
  0) clear;exit;;
  *) echo -e "${RED}\nInvalid Option. Press Enter to return back to the menu${ENDCOLOR}" ; read && shahan;;
esac
