#!/bin/bash
#By Hamed Ap
# Example : adduser hamed 123 6


sudo sed -i "/^$1:$2/d" /var/www/html/p/tarikh

sudo adduser $1 --shell /usr/sbin/nologin &
wait

sudo passwd $1 <<!
$2
$2
!

date=$(date '+%Y-%m-%d')
echo "$1:$2:$date:$3" >> /var/www/html/p/tarikh
